-- CreateTable
CREATE TABLE `billinStatement` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `forvalId` VARCHAR(191) NULL,
    `syshanId` VARCHAR(191) NULL,
    `fitId` VARCHAR(191) NULL,
    `supplyNumber` VARCHAR(191) NULL,
    `userName` VARCHAR(191) NULL,
    `status` INTEGER NULL,
    `paymentMonth` INTEGER NULL,
    `startDay` INTEGER NULL,
    `endDay` INTEGER NULL,
    `useAmount` INTEGER NULL,
    `electricityCharge` INTEGER NULL,
    `electricityChargeGovernment` INTEGER NULL,
    `electricityChargeTax` INTEGER NULL,
    `recycledEnergy` INTEGER NULL,
    `recycledEnergyGovernment` INTEGER NULL,
    `recycledEnergyTax` INTEGER NULL,
    `expenses` INTEGER NULL,
    `expensesGovernment` INTEGER NULL,
    `expensesTax` INTEGER NULL,
    `government` INTEGER NULL,
    `governmentGovernment` INTEGER NULL,
    `governmentTax` INTEGER NULL,
    `CO2Discharge` VARCHAR(191) NULL,
    `parentId` VARCHAR(191) NULL,
    `childId` VARCHAR(191) NULL,
    `created` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated` DATETIME(3) NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
